services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-db
    environment:
      - 'MYSQL_DATABASE=puls_miasta'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=user'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: phpmyadmin-gui
    ports:
      - '8081:80'
    environment:
      - 'PMA_HOST=mysql'
      - 'PMA_USER=user'
      - 'PMA_PASSWORD=password'
    depends_on:
      - mysql
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  api:
    image: eclipse-temurin:21-jdk-jammy
    container_name: java-backend
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=docker
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data: