package com.github.PulsMiastaApp.PulsMiasta.Security.WebAuthn.Service;

import com.github.PulsMiastaApp.PulsMiasta.Security.WebAuthn.Config.WebAuthnProperties;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Component;

import java.security.SecureRandom;
import java.time.Duration;
import java.util.Base64;
import java.util.Optional;

/**
 * Stores WebAuthn ceremony challenges in Redis with a short TTL.
 * <p>
 * A challenge is a 32-byte cryptographically random value generated by the server
 * and sent to the client. The client signs it with the private key; the server
 * verifies the signature against the challenge stored here.
 * <p>
 * Key format: {@code passkey_challenge:<sessionKey>}
 * Value: Base64url-encoded challenge bytes.
 * <p>
 * The sessionKey is:
 * - For registration:     the authenticated user's session token (auth_token cookie value)
 * - For authentication:   a short random token returned to the client as part of the begin response,
 * so it can be echoed back in the finish request
 */
@Component
public class ChallengeStore {

    private static final String PREFIX = "passkey_challenge:";
    private static final int CHALLENGE_BYTES = 32;

    private final StringRedisTemplate redis;
    private final Duration ttl;
    private final SecureRandom secureRandom = new SecureRandom();

    public ChallengeStore(StringRedisTemplate redis, WebAuthnProperties props) {
        this.redis = redis;
        this.ttl = Duration.ofSeconds(props.getChallengeTtlSeconds());
    }

    /**
     * Generates a new random challenge, stores it under the given session key, and returns it.
     *
     * @param sessionKey opaque key scoping this challenge to a client session
     * @return raw challenge bytes (32 bytes)
     */
    public byte[] generateAndStore(String sessionKey) {
        byte[] challenge = new byte[CHALLENGE_BYTES];
        secureRandom.nextBytes(challenge);
        String encoded = Base64.getUrlEncoder().withoutPadding().encodeToString(challenge);
        redis.opsForValue().set(PREFIX + sessionKey, encoded, ttl);
        return challenge;
    }

    /**
     * Retrieves and immediately deletes the challenge for the given session key (use-once).
     *
     * @param sessionKey the key used in {@link #generateAndStore}
     * @return the raw challenge bytes, or empty if expired / not found
     */
    public Optional<byte[]> consumeChallenge(String sessionKey) {
        String key = PREFIX + sessionKey;
        String encoded = redis.opsForValue().getAndDelete(key);
        if (encoded == null) {
            return Optional.empty();
        }
        return Optional.of(Base64.getUrlDecoder().decode(encoded));
    }
}
